apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cab-request-handler.fullname" . }}
  labels:
    {{- include "cab-request-handler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cab-request-handler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cab-request-handler.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service.enabled }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "cab-request-handler.fullname" . }}
            {{- range .Values.env.secretRefs }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
