ingress:
  enabled: true
  className: nginx
  path: /api/v1/cab

env:
  plain:
    SERVICE_NAME: cab-request-handler
    HTTP_ADDR: ":8082"
    KAFKA_BROKERS: kafka.go-ride-local.svc.cluster.local:9092
    KAFKA_TOPIC: ride.requested.v1
    DB_HOST: postgres.go-ride-local.svc.cluster.local
    DB_NAME: go_ride
    DB_PORT: "5432"
    DB_SSLMODE: disable
  secretRefs:
    - go-ride-local-secrets
