{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "websocket-gateway.fullname" . }}
  labels:
    {{- include "websocket-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "websocket-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
