{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trip-dispatch-worker.fullname" . }}
  labels:
    {{- include "trip-dispatch-worker.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.group }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.group }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "trip-dispatch-worker.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
